//! Source layers, lowest first. Every source has one explicit place.
const gantry = @import("gantry");

pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "primitives", .patterns = &.{
        "src/testing/corpus.zig",
        "src/damage.zig",
        "src/dependencies.zig",
        "src/geom.zig",
        "src/layer/**",
        "src/widgets/markdown/**",
        "src/widgets/selection.zig",
    } },
    .{ .name = "text and geometry", .patterns = &.{
        "src/cell.zig",
        "src/palette.zig",
        "src/text.zig",
        "src/winsize.zig",
    } },
    .{ .name = "capabilities and pools", .patterns = &.{
        "src/caps.zig",
        "src/pool.zig",
    } },
    .{ .name = "drawing policy", .patterns = &.{
        "src/layer.zig",
        "src/window/**",
    } },
    .{ .name = "screen", .patterns = &.{
        "src/screen.zig",
    } },
    .{ .name = "views and terminal", .patterns = &.{
        "src/render/moved_rows_impl.zig",
        "src/term.zig",
        "src/window.zig",
    } },
    .{ .name = "rendering", .patterns = &.{
        "src/render.zig",
        "src/window_test.zig",
    } },
    .{ .name = "session and scenarios", .patterns = &.{
        "src/render_budget_test.zig",
        "src/layer_test.zig",
        "src/render/moved_rows_impl_test.zig",
        "src/roundtrip_test.zig",
        "src/screen_test.zig",
        "src/session.zig",
        "src/tty.zig",
    } },
    .{ .name = "input", .patterns = &.{
        "src/input.zig",
    } },
    .{ .name = "public", .patterns = &.{
        "src/visor.zig",
    } },
    .{ .name = "widget geometry", .patterns = &.{
        "src/testing/widget_harness.zig",
        "src/widgets/layout.zig",
        "src/widgets/canvas/**",
    } },
    .{ .name = "widget views", .patterns = &.{
        "src/widgets/barchart.zig",
        "src/widgets/block.zig",
        "src/widgets/calendar.zig",
        "src/widgets/edges.zig",
        "src/widgets/gauge.zig",
        "src/widgets/keys.zig",
        "src/widgets/list.zig",
        "src/widgets/paragraph.zig",
        "src/widgets/rule.zig",
        "src/widgets/scrollbar.zig",
        "src/widgets/sextants.zig",
        "src/widgets/sparkline.zig",
        "src/widgets/table.zig",
        "src/widgets/tabs.zig",
        "src/widgets/text_input.zig",
    } },
    .{ .name = "composed widgets", .patterns = &.{
        "src/widgets/canvas.zig",
        "src/widgets/markdown.zig",
        "src/widgets/scroll.zig",
        "src/widgets/tree.zig",
    } },
    .{ .name = "widget scenarios", .patterns = &.{
        "src/widgets/canvas_test.zig",
        "src/widgets/chart.zig",
    } },
    .{ .name = "widgets", .patterns = &.{
        "src/widgets.zig",
    } },
    .{ .name = "markdown scenarios", .patterns = &.{
        "src/widgets/markdown_gfm_test.zig",
        "src/widgets/markdown_test.zig",
    } },
    .{ .name = "widget tests", .patterns = &.{
        "src/widgets_test.zig",
    } },
};

pub const entries: []const []const u8 = &.{};

pub const modules: []const gantry.NamedModule = &.{
    .{ .name = "visor", .path = "src/visor.zig", .from = "src/**" },
    .{ .name = "corpus", .path = "src/testing/corpus.zig" },
};
pub const references: []const gantry.rules.ReferenceRule = &.{
    .{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{
        "builtin",
        "conduit",
        "conduit.tty",
        "manifest",
        "morse",
        "std",
        "uucode",
    } },
    .{ .name = "source siblings", .suffix = ".zig", .relative = true, .except_targets = &.{"src/**"} },
    .{ .name = "conduit owner", .target = "conduit", .except_from = &.{"src/dependencies.zig"} },
    .{ .name = "conduit.tty owner", .target = "conduit.tty", .except_from = &.{"src/dependencies.zig"} },
    .{ .name = "morse owner", .target = "morse", .except_from = &.{"src/dependencies.zig"} },
    .{ .name = "uucode owner", .target = "uucode", .except_from = &.{"src/dependencies.zig"} },
};

pub const required = [_][]const u8{
    "src/testing/corpus.zig",
    "src/damage.zig",
    "src/dependencies.zig",
    "src/geom.zig",
    "src/layer/shm.zig",
    "src/widgets/markdown/markdown_reader.zig",
    "src/widgets/selection.zig",
    "src/cell.zig",
    "src/palette.zig",
    "src/text.zig",
    "src/winsize.zig",
    "src/caps.zig",
    "src/pool.zig",
    "src/layer.zig",
    "src/window/window_impl.zig",
    "src/screen.zig",
    "src/render/moved_rows_impl.zig",
    "src/term.zig",
    "src/window.zig",
    "src/render.zig",
    "src/window_test.zig",
    "src/render_budget_test.zig",
    "src/layer_test.zig",
    "src/render/moved_rows_impl_test.zig",
    "src/roundtrip_test.zig",
    "src/screen_test.zig",
    "src/session.zig",
    "src/tty.zig",
    "src/input.zig",
    "src/visor.zig",
    "src/testing/widget_harness.zig",
    "src/widgets/layout.zig",
    "src/widgets/canvas/raster.zig",
    "src/widgets/barchart.zig",
    "src/widgets/block.zig",
    "src/widgets/calendar.zig",
    "src/widgets/edges.zig",
    "src/widgets/gauge.zig",
    "src/widgets/keys.zig",
    "src/widgets/list.zig",
    "src/widgets/paragraph.zig",
    "src/widgets/rule.zig",
    "src/widgets/scrollbar.zig",
    "src/widgets/sextants.zig",
    "src/widgets/sparkline.zig",
    "src/widgets/table.zig",
    "src/widgets/tabs.zig",
    "src/widgets/text_input.zig",
    "src/widgets/canvas.zig",
    "src/widgets/markdown.zig",
    "src/widgets/scroll.zig",
    "src/widgets/tree.zig",
    "src/widgets/canvas_test.zig",
    "src/widgets/chart.zig",
    "src/widgets.zig",
    "src/widgets/markdown_gfm_test.zig",
    "src/widgets/markdown_test.zig",
    "src/widgets_test.zig",
};

/// Tokens only their owners may spell. The console and the terminal's
/// modes are conduit's: visor reaches them through `conduit.tty`.
pub const owned: []const gantry.rules.TokenRule = &.{
    .{ .name = "console owner", .token = "CreateFileW" },
    .{ .name = "console owner", .token = "ReadConsoleInputW" },
    .{ .name = "console owner", .token = "GetConsoleMode" },
    .{ .name = "console owner", .token = "SetConsoleMode" },
    .{ .name = "console owner", .kind = .string, .token = "CONIN$" },
    .{ .name = "console owner", .kind = .string, .token = "CONOUT$" },
    .{ .name = "console owner", .kind = .string, .token = "kernel32" },
    .{ .name = "terminal mode owner", .token = "tcsetattr" },
    .{ .name = "terminal mode owner", .token = "ioctl" },
};
